### ISSUE TITLE
Import Deployment

### ISSUE THREAD

**Issue by worzie** [jvillalobos/CTP-Manager#18]
I'm using CCK2 for custom configuration in a silent deployment. Does a generated whitelist ctpm-installer.xpi require the CTP-Manager first before the import?  After installing the generated installer I do not see a new extension like I do with CTP-Manager.
I can manually install an import xpi that prompts the warning prior to installing, but, I'm unsure it has installed.  What can I look for to verify this import and can it be done without user intervention?

Thanks for needed features!

**Comment by jvillalobos** [comment]
The generated installer is designed to make the whitelist changes and then remove itself immediately, since there's no need for it to stay around. They don't require CTP Manager to be previously installed.

To verify that the additions were made, you should check permissions.sqlite in the profile folder. You could either query the file or maybe just rely on its size being larger than the default. Or you could also deploy the profile with the already modified permissions.sqlite file, which is something CCK probably can do.

**Comment by worzie** [comment]
Very good; thanks for the clarification!  

Since deploying to a small number of testers, I had one who has firebug installed say the alert and warning messages come up for him to allow.  But it has been a silent deployment so far!

Awesome tool, thanks!

**Comment by jvillalobos** [comment]
Cool, glad it worked.
